// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dmarins/otel-challenge-go/internal/infrastructure/repositories"
	"github.com/dmarins/otel-challenge-go/internal/infrastructure/web/handlers"
	"github.com/dmarins/otel-challenge-go/internal/usecase"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

func NewGetWeatherByZipcodeInApiBUseCase(httpClient *http.Client) *usecase.GetWeatherByZipcodeInApiBUseCase {
	apiBRepository := repositories.NewApiBRepository(httpClient)
	getWeatherByZipcodeInApiBUseCase := usecase.NewGetWeatherByZipcodeInApiBUseCase(apiBRepository)
	return getWeatherByZipcodeInApiBUseCase
}

func NewZipcodeHttpHandler(getWeatherByZipcodeInApiBUseCase usecase.GetWeatherByZipcodeInApiBUseCase) *handlers.ZipcodeHttpHandler {
	zipcodeHttpHandler := handlers.NewZipcodeHttpHandler(getWeatherByZipcodeInApiBUseCase)
	return zipcodeHttpHandler
}

// wire.go:

var setApiBRepository = wire.NewSet(repositories.NewApiBRepository, wire.Bind(new(repositories.ApiBRepositoryInterface), new(*repositories.ApiBRepository)))
