services:
  ms-a:
    container_name: ms-a
    build: ./ms-a
    ports:
      - "8080:8080"
    depends_on:
      - ms-b

  ms-b:
    container_name: ms-b
    build: ./ms-b
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55681:55681"
      - "8888:8888"
    depends_on:
      - zipkin

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
